import type {
  ChangeOrder,
  Bill,
  Client,
  Invoice,
  Lead,
  Project,
  ProjectComment,
  ProjectDailyLog,
  ProjectFile,
  ProjectFinancialTarget,
  ProjectPhoto,
  ProjectRfi,
  ProjectSelection,
  ProjectTask,
  ProjectVendorAssignment,
  ProjectUpdate,
  Proposal,
  PurchaseOrder,
  TimeEntry,
  Vendor,
  WarrantyItem,
  Worker,
} from "./types";

export const clients: Client[] = [
  { id: "client-1", name: "Avery Thompson", email: "avery@example.com", phone: "(970) 555-0181" },
  { id: "client-2", name: "Morgan Ridge", email: "morgan@example.com", phone: "(970) 555-0194" },
  { id: "client-3", name: "Summit Creek Holdings", email: "projects@summitcreek.example", phone: "(970) 555-0167" },
];

export const leads: Lead[] = [
  {
    id: "lead-1",
    name: "Danielle Porter",
    email: "danielle@example.com",
    phone: "(970) 555-0142",
    projectType: "Custom Home",
    budgetRange: "$900k-$1.2M",
    status: "qualified",
    nextFollowUp: "2026-05-12",
    notes: "Interested in a modern ranch layout near Windsor.",
  },
  {
    id: "lead-2",
    name: "Chris Valdez",
    email: "chris@example.com",
    phone: "(970) 555-0178",
    projectType: "Kitchen Remodel",
    budgetRange: "$120k-$180k",
    status: "contacted",
    nextFollowUp: "2026-05-10",
    notes: "Wants premium finishes and a tighter construction window.",
  },
  {
    id: "lead-3",
    name: "Harper Stone",
    email: "harper@example.com",
    phone: "(970) 555-0126",
    projectType: "Addition",
    budgetRange: "$250k-$350k",
    status: "proposal",
    nextFollowUp: "2026-05-15",
    notes: "Needs garage and guest suite pricing separated.",
  },
  {
    id: "lead-4",
    name: "Northline Dental",
    email: "buildout@northline.example",
    phone: "(970) 555-0118",
    projectType: "Commercial Buildout",
    budgetRange: "$450k-$650k",
    status: "new",
    nextFollowUp: "2026-05-09",
    notes: "Commercial tenant improvement inquiry.",
  },
  {
    id: "lead-5",
    name: "Elena Morris",
    email: "elena@example.com",
    phone: "(970) 555-0155",
    projectType: "Whole Home Remodel",
    budgetRange: "$500k-$750k",
    status: "won",
    nextFollowUp: "2026-05-20",
    notes: "Approved design discovery retainer.",
  },
];

export const projects: Project[] = [
  {
    id: "project-1",
    clientId: "client-1",
    name: "Highland Ridge Custom Home",
    location: "Windsor, CO",
    type: "Custom Home",
    status: "active",
    currentPhase: "Interior rough-in",
    progress: 58,
    budgetRange: "$950k-$1.15M",
    startDate: "2026-02-03",
    estimatedCompletion: "2026-09-18",
    notes: "Demo project showing owner-ready progress updates and internal controls.",
    heroImage: "/images/project-3/exterior-twilight-front.jpg",
    phases: [
      { id: "phase-1", title: "Preconstruction", description: "Selections, budget alignment, and schedule lock.", status: "completed", dateLabel: "Feb 2026" },
      { id: "phase-2", title: "Foundation & Framing", description: "Foundation, framing, and dried-in milestone.", status: "completed", dateLabel: "Mar 2026" },
      { id: "phase-3", title: "Interior Rough-In", description: "MEP rough-in, inspections, and coordination notes.", status: "in-progress", dateLabel: "May 2026" },
      { id: "phase-4", title: "Finishes", description: "Cabinetry, flooring, tile, and fixture installation.", status: "upcoming", dateLabel: "Summer 2026" },
    ],
  },
  {
    id: "project-2",
    clientId: "client-2",
    name: "Poudre Canyon Mountain Modern",
    location: "Bellvue, CO",
    type: "Mountain Custom Home",
    status: "active",
    currentPhase: "Exterior completion",
    progress: 76,
    budgetRange: "$780k-$940k",
    startDate: "2025-11-10",
    estimatedCompletion: "2026-07-22",
    notes: "Demo project focused on remote-site progress photos and document tracking.",
    heroImage: "/images/project-2/exterior-front-facade.jpg",
    phases: [
      { id: "phase-1", title: "Site Prep", description: "Drive, utilities, and site staging.", status: "completed", dateLabel: "Nov 2025" },
      { id: "phase-2", title: "Shell", description: "Framing, siding, roofing, and windows.", status: "completed", dateLabel: "Feb 2026" },
      { id: "phase-3", title: "Exterior Completion", description: "Exterior punch and weatherproofing details.", status: "in-progress", dateLabel: "May 2026" },
      { id: "phase-4", title: "Final Walkthrough", description: "Owner walkthrough and warranty packet.", status: "upcoming", dateLabel: "Jul 2026" },
    ],
  },
  {
    id: "project-3",
    clientId: "client-3",
    name: "Timnath Commercial Buildout",
    location: "Timnath, CO",
    type: "Commercial",
    status: "planning",
    currentPhase: "Preconstruction",
    progress: 18,
    budgetRange: "$420k-$560k",
    startDate: "2026-06-01",
    estimatedCompletion: "2026-11-15",
    notes: "Demo commercial workflow for documents, budget line items, and follow-ups.",
    heroImage: "/images/project-1/exterior-1.jpg",
    phases: [
      { id: "phase-1", title: "Preconstruction", description: "Scope, bids, and submittals.", status: "in-progress", dateLabel: "May 2026" },
      { id: "phase-2", title: "Permits", description: "Permit and inspection workflow.", status: "upcoming", dateLabel: "Jun 2026" },
      { id: "phase-3", title: "Buildout", description: "Framing, MEP, finishes, and turnover.", status: "upcoming", dateLabel: "Summer 2026" },
    ],
  },
];

export const projectFiles: ProjectFile[] = [
  {
    id: "file-1",
    projectId: "project-1",
    name: "Rough-in inspection packet.pdf",
    type: "document",
    visibility: "internal",
    storageBucket: "project-documents",
    storagePath: "project-1/documents/rough-in-inspection-packet.pdf",
    uploadedAt: "2026-05-04",
    sizeLabel: "1.8 MB",
  },
  {
    id: "file-2",
    projectId: "project-1",
    name: "Kitchen progress photo set",
    type: "photo",
    visibility: "customer",
    storageBucket: "project-photos",
    storagePath: "project-1/photos/kitchen-progress.jpg",
    uploadedAt: "2026-05-05",
    sizeLabel: "12 photos",
  },
  {
    id: "file-3",
    projectId: "project-2",
    name: "Exterior punch notes.pdf",
    type: "document",
    visibility: "internal",
    storageBucket: "project-documents",
    storagePath: "project-2/documents/exterior-punch-notes.pdf",
    uploadedAt: "2026-05-02",
    sizeLabel: "420 KB",
  },
  {
    id: "file-4",
    projectId: "project-3",
    name: "Preconstruction estimate.pdf",
    type: "document",
    visibility: "customer",
    storageBucket: "project-documents",
    storagePath: "project-3/documents/preconstruction-estimate.pdf",
    uploadedAt: "2026-04-28",
    sizeLabel: "936 KB",
  },
];

export const projectFinancialTargets: ProjectFinancialTarget[] = [
  {
    projectId: "project-1",
    contractValue: 1050000,
    budgetedCost: 790000,
    targetMarginPercent: 22,
    contingencyPercent: 5,
    updatedAt: "2026-05-14T12:00:00Z",
  },
  {
    projectId: "project-2",
    contractValue: 860000,
    budgetedCost: 665000,
    targetMarginPercent: 20,
    contingencyPercent: 4,
    updatedAt: "2026-05-14T12:00:00Z",
  },
  {
    projectId: "project-3",
    contractValue: 520000,
    budgetedCost: 430000,
    targetMarginPercent: 18,
    contingencyPercent: 6,
    updatedAt: "2026-05-14T12:00:00Z",
  },
];

export const projectPhotos: ProjectPhoto[] = [
  {
    id: "photo-1",
    projectId: "project-1",
    title: "Kitchen rough-in progress",
    photoDate: "2026-05-14",
    category: "progress",
    visibility: "customer",
    imageUrl: "/images/project-3/kitchen-overview.jpg",
    caption: "Rough-in wall prep and kitchen layout progress before insulation.",
    uploadedAt: "2026-05-14T15:30:00-06:00",
  },
  {
    id: "photo-2",
    projectId: "project-1",
    title: "Primary bath backing check",
    photoDate: "2026-05-14",
    category: "issue",
    visibility: "internal",
    imageUrl: "/images/project-3/interior-primary-bath.jpg",
    caption: "Internal backing verification before drywall.",
    uploadedAt: "2026-05-14T16:00:00-06:00",
  },
  {
    id: "photo-3",
    projectId: "project-2",
    title: "Exterior closeout elevation",
    photoDate: "2026-05-13",
    category: "closeout",
    visibility: "customer",
    imageUrl: "/images/project-2/exterior-front-facade.jpg",
    caption: "Front elevation trim and fixture closeout progress.",
    uploadedAt: "2026-05-13T14:00:00-06:00",
  },
];

export const projectUpdates: ProjectUpdate[] = [
  {
    id: "update-1",
    projectId: "project-1",
    title: "Rough-in inspection passed",
    body: "Electrical and plumbing rough-ins passed inspection. Insulation prep is next.",
    visibility: "customer",
    updateDate: "2026-05-13",
    createdAt: "2026-05-13T10:00:00-06:00",
  },
  {
    id: "update-2",
    projectId: "project-1",
    title: "Internal blocking list",
    body: "Verify backing in primary bath before drywall.",
    visibility: "internal",
    updateDate: "2026-05-13",
    createdAt: "2026-05-13T11:00:00-06:00",
  },
];

export const projectComments: ProjectComment[] = [
  {
    id: "comment-1",
    projectId: "project-1",
    authorName: "Avery Thompson",
    body: "Client approved the tile direction during the site walk.",
    visibility: "customer",
    createdAt: "2026-05-14T09:00:00-06:00",
  },
  {
    id: "comment-2",
    projectId: "project-1",
    authorName: "Caleb Morgan",
    body: "Hold drywall until primary bath backing is verified.",
    visibility: "internal",
    createdAt: "2026-05-14T10:15:00-06:00",
  },
  {
    id: "comment-3",
    projectId: "project-2",
    authorName: "Mia Santos",
    body: "Exterior punch notes sent to the trim crew.",
    visibility: "internal",
    createdAt: "2026-05-13T16:30:00-06:00",
  },
];

export const projectTasks: ProjectTask[] = [
  {
    id: "task-1",
    projectId: "project-1",
    assignedWorkerId: "worker-2",
    title: "Confirm cabinet layout",
    notes: "Review final island and perimeter cabinet layout before ordering.",
    status: "open",
    priority: "high",
    dueDate: "2026-05-18",
    createdAt: "2026-05-13T09:30:00-06:00",
    completedAt: null,
  },
  {
    id: "task-2",
    projectId: "project-1",
    assignedWorkerId: "worker-1",
    title: "Verify primary bath backing",
    notes: "Confirm towel bar and glass panel backing before drywall.",
    status: "in-progress",
    priority: "normal",
    dueDate: "2026-05-16",
    createdAt: "2026-05-12T14:00:00-06:00",
    completedAt: null,
  },
  {
    id: "task-3",
    projectId: "project-2",
    assignedWorkerId: "worker-3",
    title: "Exterior punch walkthrough",
    notes: "Document remaining siding and trim punch items.",
    status: "open",
    priority: "normal",
    dueDate: "2026-05-20",
    createdAt: "2026-05-12T11:30:00-06:00",
    completedAt: null,
  },
];

export const projectSelections: ProjectSelection[] = [
  {
    id: "selection-1",
    projectId: "project-1",
    category: "Cabinets",
    title: "Kitchen cabinet package",
    allowanceAmount: 32000,
    selectedOption: "White oak slab fronts",
    vendor: "Front Range Cabinetry",
    dueDate: "2026-05-27",
    status: "submitted",
    internalNotes: "Confirm island panel detail before release.",
    clientNotes: "Warm white oak direction is under review.",
    createdAt: "2026-05-14T09:00:00-06:00",
    approvedAt: null,
    approvedByName: "",
  },
  {
    id: "selection-2",
    projectId: "project-1",
    category: "Tile",
    title: "Primary bath floor tile",
    allowanceAmount: 4200,
    selectedOption: "Large format porcelain",
    vendor: "Flooring Studio",
    dueDate: "2026-05-29",
    status: "approved",
    internalNotes: "Order after waterproofing inspection.",
    clientNotes: "Warm gray finish approved.",
    createdAt: "2026-05-14T10:00:00-06:00",
    approvedAt: "2026-05-14T10:45:00-06:00",
    approvedByName: "Avery Thompson",
  },
  {
    id: "selection-3",
    projectId: "project-2",
    category: "Exterior",
    title: "Front entry fixture",
    allowanceAmount: 1800,
    selectedOption: "Black steel lantern",
    vendor: "Lighting Collective",
    dueDate: "2026-05-24",
    status: "ordered",
    internalNotes: "Verify box height before install.",
    clientNotes: "Fixture has been ordered.",
    createdAt: "2026-05-13T13:00:00-06:00",
    approvedAt: "2026-05-13T15:15:00-06:00",
    approvedByName: "Morgan Ridge",
  },
];

export const projectRfis: ProjectRfi[] = [
  {
    id: "rfi-1",
    projectId: "project-1",
    title: "Clarify shower niche layout",
    question: "Should the niche align with the valve wall or center on the tile field?",
    answer: "",
    requestedBy: "Caleb Jensen",
    dueDate: "2026-05-24",
    status: "open",
    visibility: "internal",
    createdAt: "2026-05-14T08:30:00-06:00",
    answeredAt: null,
  },
  {
    id: "rfi-2",
    projectId: "project-1",
    title: "Kitchen pendant spacing",
    question: "Confirm final pendant spacing over island before electrical trim.",
    answer: "Use equal spacing centered over the island seating zone.",
    requestedBy: "Maya Torres",
    dueDate: "2026-05-21",
    status: "answered",
    visibility: "customer",
    createdAt: "2026-05-13T12:00:00-06:00",
    answeredAt: "2026-05-14T11:30:00-06:00",
  },
];

export const dailyLogs: ProjectDailyLog[] = [
  {
    id: "daily-log-1",
    projectId: "project-1",
    reportDate: "2026-05-14",
    superintendent: "Caleb Jensen",
    weather: "Clear, 68F",
    crewCount: 6,
    workPerformed: "Framing crew completed blocking, porch lid framing, and rough-in coordination.",
    deliveries: "Window flashing and LVL package delivered to the garage bay.",
    inspections: "Rough framing inspection packet is being prepared for the next site visit.",
    delays: "No delays reported.",
    safetyNotes: "Reviewed ladder setup and clean walk paths during the morning huddle.",
    nextSteps: "Complete porch framing, verify backing locations, and stage inspection photos.",
    visibility: "customer",
    createdAt: "2026-05-14T15:00:00-06:00",
  },
  {
    id: "daily-log-2",
    projectId: "project-1",
    reportDate: "2026-05-13",
    superintendent: "Maya Torres",
    weather: "Partly cloudy, 61F",
    crewCount: 4,
    workPerformed: "Coordinated cabinet field measurements and interior rough-in notes.",
    deliveries: "No deliveries.",
    inspections: "No inspections.",
    delays: "Waiting on final cabinet confirmation before release.",
    safetyNotes: "Internal reminder to keep entry protection taped down.",
    nextSteps: "Confirm cabinet layout and issue ordering notes.",
    visibility: "internal",
    createdAt: "2026-05-13T15:30:00-06:00",
  },
  {
    id: "daily-log-3",
    projectId: "project-2",
    reportDate: "2026-05-14",
    superintendent: "Eli Brooks",
    weather: "Windy, 55F",
    crewCount: 3,
    workPerformed: "Exterior trim crew advanced punch items on the front elevation.",
    deliveries: "Lighting fixture package received.",
    inspections: "Exterior closeout review planned.",
    delays: "High winds slowed ladder work in the afternoon.",
    safetyNotes: "Paused upper elevation work during wind gusts.",
    nextSteps: "Finish trim punch and document fixture locations.",
    visibility: "customer",
    createdAt: "2026-05-14T16:00:00-06:00",
  },
];

export const workers: Worker[] = [
  { id: "worker-1", name: "Caleb Jensen", role: "Lead Carpenter", status: "active" },
  { id: "worker-2", name: "Maya Torres", role: "Project Coordinator", status: "active" },
  { id: "worker-3", name: "Eli Brooks", role: "Finish Carpenter", status: "active" },
  { id: "worker-4", name: "Noah Reed", role: "Field Support", status: "inactive" },
];

export const timeEntries: TimeEntry[] = [
  { id: "time-1", workerId: "worker-1", projectId: "project-1", clockIn: "2026-05-06T07:12:00-06:00", clockOut: "2026-05-06T15:48:00-06:00", notes: "Interior blocking and coordination." },
  { id: "time-2", workerId: "worker-2", projectId: "project-1", clockIn: "2026-05-06T08:00:00-06:00", clockOut: "2026-05-06T12:30:00-06:00", notes: "Updated selections and owner notes." },
  { id: "time-3", workerId: "worker-3", projectId: "project-2", clockIn: "2026-05-06T06:45:00-06:00", clockOut: null, notes: "Active shift demo." },
  { id: "time-4", workerId: "worker-1", projectId: "project-3", clockIn: "2026-05-05T09:00:00-06:00", clockOut: "2026-05-05T13:15:00-06:00", notes: "Preconstruction walkthrough." },
];

export const invoices: Invoice[] = [
  {
    id: "invoice-1",
    invoiceNumber: "KBC-2026-001",
    projectId: "project-1",
    clientId: "client-1",
    status: "sent",
    issueDate: "2026-05-07",
    dueDate: "2026-05-22",
    notes: "Demo invoice for platform walkthrough. Payment instructions will be finalized before production use.",
    lineItems: [
      { id: "line-1", description: "Interior rough-in labor", quantity: 42.5, unitPrice: 86 },
      { id: "line-2", description: "MEP coordination allowance", quantity: 1, unitPrice: 2800 },
      { id: "line-3", description: "Site protection materials", quantity: 1, unitPrice: 740 },
    ],
  },
  {
    id: "invoice-2",
    invoiceNumber: "KBC-2026-002",
    projectId: "project-2",
    clientId: "client-2",
    status: "sent",
    issueDate: "2026-05-01",
    dueDate: "2026-05-16",
    notes: "Demo exterior milestone invoice.",
    lineItems: [
      { id: "line-1", description: "Exterior punch labor", quantity: 31, unitPrice: 82 },
      { id: "line-2", description: "Metal siding closeout materials", quantity: 1, unitPrice: 1900 },
    ],
  },
];

export const purchaseOrders: PurchaseOrder[] = [
  {
    id: "po-1",
    projectId: "project-1",
    poNumber: "KBPO-2026-001",
    title: "Cabinet deposit",
    vendor: "Front Range Cabinetry",
    amount: 18500,
    status: "sent",
    dueDate: "2026-05-30",
    notes: "Deposit to release shop drawings.",
    createdAt: "2026-05-14T09:45:00-06:00",
  },
  {
    id: "po-2",
    projectId: "project-2",
    poNumber: "KBPO-2026-002",
    title: "Exterior fixture package",
    vendor: "Lighting Collective",
    amount: 4200,
    status: "approved",
    dueDate: "2026-05-22",
    notes: "Fixtures approved for front elevation.",
    createdAt: "2026-05-13T15:30:00-06:00",
  },
];

export const bills: Bill[] = [
  {
    id: "bill-1",
    projectId: "project-1",
    billNumber: "BILL-1042",
    vendor: "Rocky Mountain Tile",
    amount: 2400.5,
    status: "received",
    dueDate: "2026-06-05",
    notes: "Tile material invoice.",
    createdAt: "2026-05-14T12:00:00-06:00",
  },
  {
    id: "bill-2",
    projectId: "project-2",
    billNumber: "BILL-1043",
    vendor: "Foothills Metal",
    amount: 6100,
    status: "draft",
    dueDate: "2026-05-28",
    notes: "Exterior metal closeout material.",
    createdAt: "2026-05-13T13:15:00-06:00",
  },
];

export const changeOrders: ChangeOrder[] = [
  {
    id: "change-order-1",
    changeOrderNumber: "KBCO-2026-001",
    projectId: "project-1",
    clientId: "client-1",
    title: "Covered Patio Expansion",
    status: "sent",
    reason: "Owner requested a larger covered outdoor living area after framing review.",
    scheduleImpactDays: 5,
    clientMessage:
      "This change order adds covered patio framing, roof tie-in labor, and electrical prep for future heaters.",
    internalNotes: "Confirm beam lead time and roof flashing details before sending.",
    createdAt: "2026-05-13T09:30:00-06:00",
    approvedAt: null,
    approvedByName: "",
    lineItems: [
      { id: "co-line-1", description: "Patio framing labor", quantity: 18, unitPrice: 92 },
      { id: "co-line-2", description: "Roof tie-in material allowance", quantity: 1, unitPrice: 4200 },
      { id: "co-line-3", description: "Electrical rough-in allowance", quantity: 1, unitPrice: 2400 },
    ],
  },
];

export const vendors: Vendor[] = [
  {
    id: "vendor-1",
    name: "Front Range Cabinetry",
    companyType: "subcontractor",
    trade: "Cabinetry",
    email: "schedule@frcabinetry.example",
    phone: "(970) 555-0199",
    status: "active",
    portalAccess: true,
    notes: "Preferred cabinet partner for custom cabinet packages.",
    createdAt: "2026-05-14T09:00:00-06:00",
  },
  {
    id: "vendor-2",
    name: "Rocky Mountain Tile",
    companyType: "subcontractor",
    trade: "Tile",
    email: "dispatch@rmtile.example",
    phone: "(970) 555-0188",
    status: "active",
    portalAccess: true,
    notes: "Tile install partner for bath and kitchen finish work.",
    createdAt: "2026-05-13T10:00:00-06:00",
  },
  {
    id: "vendor-3",
    name: "Lighting Collective",
    companyType: "vendor",
    trade: "Lighting",
    email: "orders@lightingcollective.example",
    phone: "(970) 555-0177",
    status: "active",
    portalAccess: false,
    notes: "Lighting and fixture supplier.",
    createdAt: "2026-05-12T10:00:00-06:00",
  },
];

export const projectVendorAssignments: ProjectVendorAssignment[] = [
  {
    id: "vendor-assignment-1",
    projectId: "project-1",
    vendorId: "vendor-1",
    scope: "Cabinet layout, shop drawings, and install coordination.",
    startDate: "2026-05-20",
    endDate: "2026-06-12",
    status: "active",
    visibility: "customer",
    createdAt: "2026-05-14T09:30:00-06:00",
  },
  {
    id: "vendor-assignment-2",
    projectId: "project-1",
    vendorId: "vendor-2",
    scope: "Primary bath floor tile prep and installation.",
    startDate: "2026-05-28",
    endDate: "2026-06-07",
    status: "scheduled",
    visibility: "internal",
    createdAt: "2026-05-14T10:00:00-06:00",
  },
  {
    id: "vendor-assignment-3",
    projectId: "project-2",
    vendorId: "vendor-3",
    scope: "Exterior fixture package coordination.",
    startDate: "2026-05-17",
    endDate: "2026-05-24",
    status: "scheduled",
    visibility: "customer",
    createdAt: "2026-05-13T12:00:00-06:00",
  },
];

export const warrantyItems: WarrantyItem[] = [
  {
    id: "warranty-1",
    projectId: "project-1",
    itemType: "punch-list",
    title: "Adjust primary bath door reveal",
    description: "Door rubs slightly at the strike side casing.",
    location: "Primary bath",
    requestedBy: "Avery Thompson",
    status: "open",
    priority: "normal",
    dueDate: "2026-06-04",
    visibility: "customer",
    createdAt: "2026-05-14T12:00:00-06:00",
    resolvedAt: null,
  },
  {
    id: "warranty-2",
    projectId: "project-1",
    itemType: "warranty",
    title: "Touch up mudroom drywall",
    description: "Small drywall touch-up beside the mudroom bench.",
    location: "Mudroom",
    requestedBy: "Avery Thompson",
    status: "scheduled",
    priority: "low",
    dueDate: "2026-06-07",
    visibility: "customer",
    createdAt: "2026-05-14T13:00:00-06:00",
    resolvedAt: null,
  },
  {
    id: "warranty-3",
    projectId: "project-2",
    itemType: "punch-list",
    title: "Exterior trim paint check",
    description: "Verify south elevation touch-up after final siding walkthrough.",
    location: "South elevation",
    requestedBy: "Maya Torres",
    status: "resolved",
    priority: "normal",
    dueDate: "2026-05-28",
    visibility: "internal",
    createdAt: "2026-05-13T11:00:00-06:00",
    resolvedAt: "2026-05-14T09:30:00-06:00",
  },
];

export const proposals: Proposal[] = [
  {
    id: "proposal-1",
    leadId: "lead-3",
    proposalNumber: "KBP-2026-001",
    title: "Garage and Guest Suite Addition",
    status: "draft",
    clientName: "Harper Stone",
    clientEmail: "harper@example.com",
    scopeSummary:
      "Preconstruction proposal for separating garage shell work from the finished guest suite scope.",
    internalNotes: "Confirm utility trenching and steel allowance before sending.",
    validUntil: "2026-06-15",
    createdAt: "2026-05-12T10:00:00-06:00",
    lineItems: [
      {
        id: "proposal-line-1",
        section: "Base Scope",
        description: "Garage framing and dried-in shell allowance",
        quantity: 1,
        unitPrice: 84000,
        isOptional: false,
      },
      {
        id: "proposal-line-2",
        section: "Guest Suite",
        description: "Interior finish allowance for guest suite",
        quantity: 1,
        unitPrice: 126000,
        isOptional: false,
      },
      {
        id: "proposal-line-3",
        section: "Optional Upgrade",
        description: "Heated bathroom floor allowance",
        quantity: 1,
        unitPrice: 3800,
        isOptional: true,
      },
    ],
  },
];
