import type { LandLead } from "./types";

/**
 * Demo leads shown when Supabase is not configured (NEXT_PUBLIC_DEMO_MODE).
 * Illustrates the range of scores, counties, and statuses the tool produces.
 */
export const landLeads: LandLead[] = [
  {
    id: "land-lead-1",
    county: "weld",
    parcelNumber: "096310400017",
    accountNumber: "R8891234",
    ownerName: "MARSHALL DANA",
    ownerNameSecondary: "MARSHALL ERIC",
    mailingAddress1: "4820 Boardwalk Dr Apt 3",
    mailingAddress2: "",
    mailingCity: "Fort Collins",
    mailingState: "CO",
    mailingZip: "80525",
    situsAddress: "35120 County Road 15",
    situsCity: "Severance",
    situsState: "CO",
    situsZip: "80550",
    acreage: 4.6,
    propertyClass: "",
    landUse: "Vacant Land",
    zoning: "AG",
    saleDate: "2026-05-18",
    salePrice: 265_000,
    deedType: "WD",
    landActualValue: 240_000,
    improvementActualValue: 0,
    totalActualValue: 240_000,
    isLikelyVacant: true,
    isEntityOwner: false,
    mailingDiffersFromSitus: true,
    inTargetMarket: true,
    leadScore: 100,
    leadReason:
      "Likely vacant land; sold within the last 180 days; owner mailing address differs from the property address; sale price above threshold; acreage in the desirable custom-home range; in a target Northern Colorado market.",
    sourceRowHash: "demo-hash-1",
    firstSeenAt: "2026-07-01T15:00:00Z",
    lastSeenAt: "2026-07-07T15:00:00Z",
    lastRefreshedAt: "2026-07-07T15:00:00Z",
    status: "new",
    notes: "",
    sourceDataset: "weld_arcgis",
  },
  {
    id: "land-lead-2",
    county: "larimer",
    parcelNumber: "8712300005",
    accountNumber: "R1120987",
    ownerName: "OKONKWO FAMILY TRUST",
    ownerNameSecondary: "",
    mailingAddress1: "PO Box 441",
    mailingAddress2: "",
    mailingCity: "Windsor",
    mailingState: "CO",
    mailingZip: "80550",
    situsAddress: "1250 Signal Tree Way",
    situsCity: "Timnath",
    situsState: "CO",
    situsZip: "80547",
    acreage: 2.1,
    propertyClass: "0100",
    landUse: "Vacant Residential",
    zoning: "RES",
    saleDate: "2026-04-02",
    salePrice: 310_000,
    deedType: "WD",
    landActualValue: 295_000,
    improvementActualValue: 0,
    totalActualValue: 295_000,
    isLikelyVacant: true,
    isEntityOwner: false,
    mailingDiffersFromSitus: true,
    inTargetMarket: true,
    leadScore: 100,
    leadReason:
      "Likely vacant land; sold within the last 180 days; owner mailing address differs from the property address; sale price above threshold; acreage in the desirable custom-home range; in a target Northern Colorado market.",
    sourceRowHash: "demo-hash-2",
    firstSeenAt: "2026-07-01T15:00:00Z",
    lastSeenAt: "2026-07-07T15:00:00Z",
    lastRefreshedAt: "2026-07-07T15:00:00Z",
    status: "reviewed",
    notes: "Owner also owns two adjacent lots — potential multi-home opportunity.",
    sourceDataset: "larimer_assessor_csv",
  },
  {
    id: "land-lead-3",
    county: "weld",
    parcelNumber: "080924100011",
    accountNumber: "R4451200",
    ownerName: "HIGH PLAINS DEVELOPMENT LLC",
    ownerNameSecondary: "",
    mailingAddress1: "700 Corporate Cir Ste 200",
    mailingAddress2: "",
    mailingCity: "Greeley",
    mailingState: "CO",
    mailingZip: "80634",
    situsAddress: "0 Weld County Road 27",
    situsCity: "Greeley",
    situsState: "CO",
    situsZip: "80631",
    acreage: 18.4,
    propertyClass: "",
    landUse: "Vacant Land",
    zoning: "AG",
    saleDate: "2026-06-20",
    salePrice: 1_150_000,
    deedType: "SWD",
    landActualValue: 980_000,
    improvementActualValue: 0,
    totalActualValue: 980_000,
    isLikelyVacant: true,
    isEntityOwner: true,
    mailingDiffersFromSitus: true,
    inTargetMarket: true,
    leadScore: 75,
    leadReason:
      "Likely vacant land; sold within the last 180 days; owner mailing address differs from the property address; sale price above threshold; acreage in the desirable custom-home range; in a target Northern Colorado market; owner looks like a company, developer, or government entity.",
    sourceRowHash: "demo-hash-3",
    firstSeenAt: "2026-07-01T15:00:00Z",
    lastSeenAt: "2026-07-07T15:00:00Z",
    lastRefreshedAt: "2026-07-07T15:00:00Z",
    status: "not_a_fit",
    notes: "Developer-owned; exclude from homeowner campaign.",
    sourceDataset: "weld_arcgis",
  },
  {
    id: "land-lead-4",
    county: "larimer",
    parcelNumber: "9634100022",
    accountNumber: "R2098771",
    ownerName: "PETERSEN KYLE",
    ownerNameSecondary: "PETERSEN AMANDA",
    mailingAddress1: "812 Sundance Cir",
    mailingAddress2: "",
    mailingCity: "Loveland",
    mailingState: "CO",
    mailingZip: "80537",
    situsAddress: "812 Sundance Cir",
    situsCity: "Loveland",
    situsState: "CO",
    situsZip: "80537",
    acreage: 0.28,
    propertyClass: "0100",
    landUse: "Vacant Residential",
    zoning: "RES",
    saleDate: "2026-03-11",
    salePrice: 145_000,
    deedType: "WD",
    landActualValue: 130_000,
    improvementActualValue: 0,
    totalActualValue: 130_000,
    isLikelyVacant: true,
    isEntityOwner: false,
    mailingDiffersFromSitus: false,
    inTargetMarket: true,
    leadScore: 65,
    leadReason:
      "Likely vacant land; sold within the last 180 days; in a target Northern Colorado market.",
    sourceRowHash: "demo-hash-4",
    firstSeenAt: "2026-07-01T15:00:00Z",
    lastSeenAt: "2026-07-07T15:00:00Z",
    lastRefreshedAt: "2026-07-07T15:00:00Z",
    status: "contacted",
    notes: "Sent first postcard 7/3.",
    sourceDataset: "larimer_assessor_csv",
  },
  {
    id: "land-lead-5",
    county: "weld",
    parcelNumber: "071508300004",
    accountNumber: "R6612345",
    ownerName: "NGUYEN THANH",
    ownerNameSecondary: "",
    mailingAddress1: "2201 W 9th St",
    mailingAddress2: "",
    mailingCity: "Berthoud",
    mailingState: "CO",
    mailingZip: "80513",
    situsAddress: "0 County Road 44",
    situsCity: "Berthoud",
    situsState: "CO",
    situsZip: "80513",
    acreage: 7.9,
    propertyClass: "",
    landUse: "Vacant Land",
    zoning: "AG",
    saleDate: "2025-10-05",
    salePrice: 220_000,
    deedType: "WD",
    landActualValue: 200_000,
    improvementActualValue: 0,
    totalActualValue: 200_000,
    isLikelyVacant: true,
    isEntityOwner: false,
    mailingDiffersFromSitus: true,
    inTargetMarket: true,
    leadScore: 70,
    leadReason:
      "Likely vacant land; owner mailing address differs from the property address; sale price above threshold; acreage in the desirable custom-home range; in a target Northern Colorado market.",
    sourceRowHash: "demo-hash-5",
    firstSeenAt: "2026-07-01T15:00:00Z",
    lastSeenAt: "2026-07-07T15:00:00Z",
    lastRefreshedAt: "2026-07-07T15:00:00Z",
    status: "new",
    notes: "",
    sourceDataset: "weld_arcgis",
  },
  {
    id: "land-lead-6",
    county: "larimer",
    parcelNumber: "8534200099",
    accountNumber: "R3345678",
    ownerName: "CITY OF FORT COLLINS",
    ownerNameSecondary: "",
    mailingAddress1: "300 Laporte Ave",
    mailingAddress2: "",
    mailingCity: "Fort Collins",
    mailingState: "CO",
    mailingZip: "80521",
    situsAddress: "0 Natural Area Rd",
    situsCity: "Fort Collins",
    situsState: "CO",
    situsZip: "80524",
    acreage: 55.2,
    propertyClass: "9100",
    landUse: "Exempt",
    zoning: "POS",
    saleDate: null,
    salePrice: null,
    deedType: "",
    landActualValue: 0,
    improvementActualValue: 0,
    totalActualValue: 0,
    isLikelyVacant: true,
    isEntityOwner: true,
    mailingDiffersFromSitus: true,
    inTargetMarket: true,
    leadScore: 0,
    leadReason:
      "Likely vacant land; owner mailing address differs from the property address; in a target Northern Colorado market; owner looks like a company, developer, or government entity; no sale date on record; very low parcel value.",
    sourceRowHash: "demo-hash-6",
    firstSeenAt: "2026-07-01T15:00:00Z",
    lastSeenAt: "2026-07-07T15:00:00Z",
    lastRefreshedAt: "2026-07-07T15:00:00Z",
    status: "do_not_contact",
    notes: "Municipal open space.",
    sourceDataset: "larimer_assessor_csv",
  },
];
